'use client'
import type { Metadata } from "next";
import React, { useState, useEffect } from "react";
import { Inter } from "next/font/google";

import Loader from "../components/common/loader/Loader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Reflections",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [loading, setLoading] = useState(true);
  useEffect(() => {
    // Simulate a loading effect, or use actual logic to determine when to hide the loader
    const timer = setTimeout(() => setLoading(false), 2000); // Example: 2 seconds delay

    return () => clearTimeout(timer);
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
      {loading && <Loader />}
      {!loading && children}
      </body>
    </html>
  );
}
